# Generated by Django 4.2.7 on 2025-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('PROCESSING', 'Ishlovda'), ('SHIPPED', 'Kutilmoqda'), ('DELIVERED', 'Yetkazildi'), ('CANCELLED', 'Bekor qilindi')], default='NEW', max_length=20, verbose_name='Status'),
        ),
    ]
