# Generated by Django 4.2.7 on 2025-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('CANCELLED', 'Bekor qilindi')], default='NEW', max_length=20, verbose_name='Status'),
        ),
    ]
