# Generated by Django 4.2.7 on 2025-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yetkazib berish sanasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PREPARING', 'Tayorgarlik'), ('IN_TRANSIT', 'Yo`lga tushdi'), ('DELIVERED', 'Yetib keldi')], default='PENDING', max_length=20, verbose_name='Yetkazib berish statusi'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Kuzatuv raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('PROCESSING', 'Ishlovda'), ('SHIPPED', 'Yuborildi'), ('DELIVERED', 'Yetkazildi'), ('CANCELLED', 'Bekor qilindi')], default='NEW', max_length=20, verbose_name='Status'),
        ),
    ]
