name: Deploy Django to EC2

on:
  push:
    branches:
      - main # Или master, если это ваша основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        # Используем printf для безопасной записи ключа
        printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 15.207.112.123 >> ~/.ssh/known_hosts # Убедитесь, что IP правильный
        chmod 644 ~/.ssh/known_hosts
      # env: # Эту строку можно удалить, так как ключ передается напрямую
      #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@15.207.112.123 "
          cd /var/www/cloth_wms_project/ # Путь к вашему проекту на сервере
          git pull origin main # Или master, если это ваша ветка
          sudo /var/www/cloth_wms_project/venv/bin/pip install -r requirements.txt # Если используете venv
          sudo /var/www/cloth_wms_project/venv/bin/python manage.py migrate
          sudo systemctl restart gunicorn
        "
